name: Cream Commission Payback

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-commission-payback:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./commission-payback
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.2.0
      - run: npm ci
      - run: npm run build
      - run: npm run start
      - run: |
          git config --global user.name "iotacreamies[bot]"
          git config --global user.email "iotacreamies@proton.me"
          git add data.json
          git commit -m "Update epoch staking data" || echo "No changes to commit"
          git push
