name: Cream Commission Payback

on:
  schedule:
    - cron: '6 11 * * *'
  workflow_dispatch:

jobs:
  run-commission-payback:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./commission-payback
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6.2.0
      - run: npm ci
      - run: npm run build
      - run: npm run start
