name: Cream Commission Payback

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  run-commission-payback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0

      - name: Go to script folder
        run: cd commission-payback

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run script
        run: npm run start
